config/routes.rb
BrunchInBrookline::Application.routes.draw do
  
  resources :signatures

  resources :petitions

  devise_for :users

  root :to => 'petitions#index'
  get 'about' => 'pages#about'

end

app/models/petition.rb
class Petition < ActiveRecord::Base
  attr_accessible :description, :name

  validates :description, presence: true
  
  has_many :users
  #signature
  has_many :signatures
  has_many :signers ,:through => :signatures , :class_name => 'User'

  def petition_supporters
  	User.all
  end


end

app/models/signature.rb
class Signature < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :signer, :class_name => 'User'
  belongs_to :petition
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  #relationsships
  has_many :petitions
  #signatures
  has_many :signatures
  has_many :signed_petitions ,:through => :signatures , :class_name => 'Petitions' , :foreign_key => 'petition_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  # GET /petitions
  # GET /petitions.json
  def index
    @petitions = Petition.all
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @petitions }
    end
  end

  # GET /petitions/1
  # GET /petitions/1.json
  def show
    @petition = Petition.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @petition }
    end
  end

  # GET /petitions/new
  # GET /petitions/new.json
  def new
    @petition = Petition.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @petition }
    end
  end

  # GET /petitions/1/edit
  def edit
    @petition = Petition.find(params[:id])
  end

  # POST /petitions
  # POST /petitions.json
  def create
    @petition = Petition.new(params[:petition])

    respond_to do |format|
      if @petition.save
        format.html { redirect_to @petition, notice: 'Petition was successfully created.' }
        format.json { render json: @petition, status: :created, location: @petition }
      else
        format.html { render action: "new" }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /petitions/1
  # PUT /petitions/1.json
  def update
    @petition = Petition.find(params[:id])

    respond_to do |format|
      if @petition.update_attributes(params[:petition])
        format.html { redirect_to @petition, notice: 'Petition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @petition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /petitions/1
  # DELETE /petitions/1.json
  def destroy
    @petition = Petition.find(params[:id])
    @petition.destroy

    respond_to do |format|
      format.html { redirect_to petitions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/signatures_controller.rb
class SignaturesController < ApplicationController
  # GET /signatures
  # GET /signatures.json
  def index
    @signatures = Signature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signatures }
    end
  end

  # GET /signatures/1
  # GET /signatures/1.json
  def show
    @signature = Signature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signature }
    end
  end

  # GET /signatures/new
  # GET /signatures/new.json
  def new
    @signature = Signature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signature }
    end
  end

  # GET /signatures/1/edit
  def edit
    @signature = Signature.find(params[:id])
  end

  # POST /signatures
  # POST /signatures.json
  def create
    @signature = Signature.new(params[:signature])

    respond_to do |format|
      if @signature.save
        format.html { redirect_to @signature, notice: 'Signature was successfully created.' }
        format.json { render json: @signature, status: :created, location: @signature }
      else
        format.html { render action: "new" }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /signatures/1
  # PUT /signatures/1.json
  def update
    @signature = Signature.find(params[:id])

    respond_to do |format|
      if @signature.update_attributes(params[:signature])
        format.html { redirect_to @signature, notice: 'Signature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signatures/1
  # DELETE /signatures/1.json
  def destroy
    @signature = Signature.find(params[:id])
    @signature.destroy

    respond_to do |format|
      format.html { redirect_to signatures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/petitions_helper.rb
module PetitionsHelper
end

app/helpers/signatures_helper.rb
module SignaturesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Brunch in Brookline", "" %>

  </small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">Brunch in Brookline</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                    </ul>
                    
                    <ul class="nav pull-right">
                        <% if user_signed_in? %>
                            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                        <% else %>
                            <li><%= link_to "Login", new_user_session_path %></li>
                        <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BrunchInBrookline</title>
  	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
  <%= tag :meta, name: "viewport", content: "width=device-width, initial-scale=1.0" %>
</head>
<body>
	<%= render 'layouts/header' %>

	<div class="container">
			<% flash.each do |name, msg| %>
	                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	        <% end %>
		<%= yield %>	
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
	<div class="center hero-unit">
	<h1>Join the brunch movement!</h1>
	<p>
	  We're bringing together the Brookline community to bring an outstanding brunch to our neighborhood. Are you in?  
	</p>
	<p>
	  <%= link_to "Sign the petition!", new_user_registration_path, class: "btn btn-large btn-primary" %>

	</p>
	</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to "Brunch in Brookline", "" %>
  is a project to bring a solid brunch to Brookline 
</p>

app/views/pages/home.html.erb
<div class="center hero-unit">
<h1>Welcome to Brunch in Brookline!</h1>
<p>
  The petition to bring a solid brunch to Brookline!
</p>
<p>
  <%= link_to "Sign the petition!", new_user_registration_path, class: "btn btn-large btn-primary" %>
</p>
</div>

app/views/petitions/_form.html.erb
<%= simple_form_for(@petition, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, as: :text, input_html: { rows: "1" } %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/petitions/_petition.html.erb
<tr>
	<td><%= petition.name %></td>
	<td><%= petition.description %></td>
	       
</tr>

<tr>
	<td></td>
</tr>

app/views/petitions/edit.html.erb
<h1>Editing petition</h1>

<%= render 'form' %>

<%= link_to 'Show', @petition %> |
<%= link_to 'Back', petitions_path %>

app/views/petitions/index.html.erb
<%= render 'pages/home' %>

<h1>Petition Supporters</h1>

<!--     <table class="table table-striped">
        <thead>
            <tr>
                <th>Full Name</th>
            </tr>
        </thead>

        <tbody> -->
           <!--  <%= render @petitions %>
        </tbody>
    </table> -->

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= user.name %>
    </li>
  <% end %>
</ul>

app/views/petitions/new.html.erb
<h1>New petition</h1>

<%= render 'form' %>

<%= link_to 'Back', petitions_path %>

app/views/petitions/show.html.erb
<div class="row">
    <div class="span6 offset3">
        <div class="well">
            <p>
              <%= @petition.description %>
            </p>
            <%= link_to 'Edit', edit_petition_path(@petition) %> |
            <%= link_to 'Back', petitions_path %>
        </div>
    </div>
</div>

app/views/signatures/_form.html.erb
<%= simple_form_for(@signature) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/signatures/edit.html.erb
<h1>Editing signature</h1>

<%= render 'form' %>

<%= link_to 'Show', @signature %> |
<%= link_to 'Back', signatures_path %>

app/views/signatures/index.html.erb
<h1>Listing signatures</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signatures.each do |signature| %>
  <tr>
    <td><%= link_to 'Show', signature %></td>
    <td><%= link_to 'Edit', edit_signature_path(signature) %></td>
    <td><%= link_to 'Destroy', signature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signature', new_signature_path %>

app/views/signatures/new.html.erb
<h1>New signature</h1>

<%= render 'form' %>

<%= link_to 'Back', signatures_path %>

app/views/signatures/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_signature_path(@signature) %> |
<%= link_to 'Back', signatures_path %>